---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/West
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/container/qbittorrent/appdata:/config
      - /mnt/data/Torrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
